### ISSUE TITLE
Unable to install ttrss

### ISSUE THREAD

**Issue by gmalets** [YunoHost-Apps/ttrss_ynh#102]
### Describe the bug

Unable to install ttrss TinyTiny-RSS

### Context

- Hardware: Old laptop or computer
- YunoHost version: 4.2.4 (stable)
- I have access to my server: Through SSH & through the webadmin & direct access via keyboard/screen

### Steps to reproduce

  ```sudo yunohost app install ttrss```

OR

   1. *Go to '.../yunohost/admin/#/apps'
   2. *Click on 'Install' (.../yunohost/admin/#/apps/catalog)
   3. *Search 'rss'
   4. Clich "Install" button on "Tiny Tiny RSS"
   5. Error will apear 

### Logs

https://paste.yunohost.org/raw/tunedixaqu

**Comment by tituspijean** [comment]
OK, so the issue lies with the files permissions (belongs to `root:root` with no read access to `$app` user. I am working on a fix.

**Comment by gmalets** [comment]
> I am working on a fix.

Thank you, sir

**Comment by gmalets** [comment]
Still doesn't work

https://paste.yunohost.org/raw/niqipoliwa

**Comment by yalh76** [comment]
Will be solved when https://github.com/YunoHost-Apps/ttrss_ynh/pull/105 will be merged
