### ISSUE TITLE
SSO login broken with 20220222~ynh1

### ISSUE THREAD

**Issue by MonsieurPoutounours** [YunoHost-Apps/ttrss_ynh#113]
Hi,

After upgrading from 20200916-ynh5 to 20220222-ynh1, SSO login is broken. 

If user is already logged in Yunohost, TT-RSS page is shown, yet it should not be. 
If user is not already logged iin Yunohost, yunohost auth page is shown, then TT-RSS auth page is shown. 

This "double authentication" also breaks mobile apps. 

Tested on Yunohost 4.3.6.2

Are there any manual migration actions needed ? 

Regards.

**Comment by ericgaspar** [comment]
Please see the conversation if you haven't : https://forum.yunohost.org/t/tiny-tiny-rss-rss-reader/3968/19

**Comment by MonsieurPoutounours** [comment]
Thank you. Changing admin password and adding TT-RSS to visitors group solved it.
