### ISSUE TITLE
Old Bug is New 

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/ttrss_ynh#115]
Hello!

this issue is cropping up for me:

https://forum.yunohost.org/t/tt-rss-cant-connect-anymore-via-any-client/9445

I've tried two different clients.

**Comment by ericgaspar** [comment]
there is some clues in the forum https://forum.yunohost.org/t/tiny-tiny-rss-rss-reader/3968/18

**Comment by brimwats** [comment]
> Can you confirm the option Activer l’API is activated in TTRSS configuration → Général

it is

> add to visitors

this worked! thanks
