### ISSUE TITLE
Can’t backup the app anymore

### ISSUE THREAD

**Issue by El-Gavy** [YunoHost-Apps/ttrss_ynh#117]
### Describe the bug

TTRSS app can’t be backed up anymore using Yunohost web admin https://forum.yunohost.org/t/tiny-tiny-rss-rss-reader/3968/41?u=gavy

### Context

- Hardware: VPS bought online 
- YunoHost version: 4.3.6.2 (stable).
- I have access to my server: Through SSH | through the webadmin.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using : 20220222~ynh1

### Steps to reproduce

   1. *Go to 'Backups menu'*
   2. *Click on 'Local'*
   3. *Create a backup including only the TTRSS app*
   4. *Backup is unsuccessful because of missing /etc/cron.d/ttrss file*

### Expected behavior

Backup is successful.

### Logs

https://paste.yunohost.org/raw/iruhedoyex

Seems to also affect Borg backups, for the same reason. (https://forum.yunohost.org/t/tiny-tiny-rss-rss-reader/3968/41?u=gavy)

**Comment by ericgaspar** [comment]
can you try in the terminal:
`touch /etc/cron.d/ttrss` and then upgrade (`/etc/cron.d/ttrss` will be deleted in the upgrade script).

**Comment by El-Gavy** [comment]
> `touch /etc/cron.d/ttrss` and then upgrade (`/etc/cron.d/ttrss`

I just did and that worked just fine.

I tried a backup : successfull! 🎆 

Thanks for your fast answer!
