### ISSUE TITLE
SSO is not working anymore

### ISSUE THREAD

**Issue by El-Gavy** [YunoHost-Apps/ttrss_ynh#118]
### Describe the bug

When logged in the YunoHost user portal and clicking on TTRSS tile, the app doesn’t recognize me. If I enter my username and password (the same used for YunoHost user portal), I logs me successfully.

### Context

- Hardware: VPS bought online 
- YunoHost version: 4.3.6.2 (stable).
- I have access to my server: Through SSH | through the webadmin.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using : 20220222~ynh1

### Steps to reproduce

   1. *Log in YunoHost user portal*
   2. *Click on the TTRSS tile*
   3. *TTRSS authentification screen is displayed*
   4. *Enter user credentials*
   5. *Login to TTRSS is successful*

### Expected behavior

When logged in YunoHost user portal, clicking on TTRSS tile should redirect to the app and log me at the same time using SSO.

### Logs

I don’t know how to extract the corresponding logs

**Comment by ericgaspar** [comment]
there is some clues in the forum https://forum.yunohost.org/t/tiny-tiny-rss-rss-reader/3968/18

**Comment by El-Gavy** [comment]
well, I logged in TTRSS using the admin account with the default password and I changed the password.

But that still doesn’t make SSO work with my personal YunoHost account. I am missing the logic here, sorry…

**Comment by ericgaspar** [comment]
> But that still doesn’t make SSO work with my personal YunoHost account. I am missing the logic here, sorry…

The applied patches that made this possible are not working anymore. For authentication we have to go through TTRSS authentication.

**Comment by El-Gavy** [comment]
ok so it is "normal" that SSO isn’t working anymore for TTRSS. Not a big deal for me, I was just afraid that something was broken! Thanks for your fast answers!

**Comment by ericgaspar** [comment]
Yes, it is a regression. I guess it's better to use TTRSS authentication instead of leaving the package far behind upstream.

**Comment by El-Gavy** [comment]
Indeed I agree with you (and as I use mainly TTRSS with an android app, that doesn’t change much for me).
