### ISSUE TITLE
Updating Bug

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/ttrss_ynh#119]
Hello!

just noting this update failure with logs:

https://paste.yunohost.org/raw/xusorahuna

**Comment by ericgaspar** [comment]
can you try in the terminal:
touch `/etc/cron.d/ttrss` and then upgrade (`/etc/cron.d/ttrss` will be deleted in the upgrade script).

**Comment by brimwats** [comment]
that worked! thanks!
