### ISSUE TITLE
 error inside upgrade script - can´t update

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/ttrss_ynh#127]
I get an error inside the upgrade script - can´t update

`ERROR - Could not upgrade ttrss: An error occurred inside the app upgrade script`

https://paste.yunohost.org/raw/exavucogiq

What could i try?

thanks for help

**Comment by ericgaspar** [comment]
can you try in the terminal:
`touch /etc/cron.d/ttrss` and then upgrade (`/etc/cron.d/ttrss` will be deleted in the upgrade script).

**Comment by rocky-III** [comment]
SUPER 
THANKS for your Help and Work  @ericgaspar
