### ISSUE TITLE
Can't fetch anymore rss feed from local website

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/ttrss_ynh#134]
Hardware: Old laptop or computer
YunoHost version: 4.3.6.3
I have access to my server : Through SSH | through the webadmin | direct access via keyboard / screen
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

Hello,
I have ttrss installed for many years now. I used to be able to get rss feed from a PluXML blog installed thanks to My WebApp hosted on the same yunohost server.
Recently, it has stop working and when I try to subscribe to the feed again, I get the following error :` L’URL spécifiée n’a pas pu être téléchargée : URL hostname failed to resolve or resolved to a loopback address (127.0.0.1)`

![image](https://user-images.githubusercontent.com/464782/175825963-b8865fd6-cd3b-43bd-8829-1cb62c315910.png)

Matériel: Vieil ordinateur
Version de YunoHost: 4.3.6.3
J’ai accès à mon serveur : En SSH | Par la webadmin | En direct avec un clavier/écran
Êtes-vous dans un contexte particulier ou avez-vous effectué des modificiations particulières sur votre instance ? : non
Description du problème

Bonsoir,
Ttrss est installé sur notre serveur Yunohost depuis de nombreuses années. J'avais l'habitude de pouvoir obtenir le flux rss d'un blog PluXML installé grâce à My WebApp hébergé sur le même serveur yunohost.
Récemment, cela a cessé de fonctionner et lorsque j'essaie de m'abonner à nouveau au flux, j'obtiens l'erreur suivante :`` L'URL spécifiée n'a pas pu être téléchargée : URL hostname failed to resolve or resolved to a loopback address (127.0.0.1)``.

![image](https://user-images.githubusercontent.com/464782/175825963-b8865fd6-cd3b-43bd-8829-1cb62c315910.png)

**Comment by ericgaspar** [comment]
This thread explains the security changes to TTRSS
https://community.tt-rss.org/t/heads-up-several-vulnerabilities-fixed/3799/7

**Comment by Thatoo** [comment]
> This thread explains the security changes to TTRSS https://community.tt-rss.org/t/heads-up-several-vulnerabilities-fixed/3799/7

Thank you. I have read. It talks about the fact that ttrss can fetch only on https:// on 443 port from now on, it can't fetch from specific port anymore.
I might not have understand it all but I didn't read something saying it can't fetch rss feed from a regular https:// url of blog that are hosted on the same yunohost server.

**Comment by Thatoo** [comment]
https://antoine.leprette.fr/site/feed.php?rss works on the demo server of ttrss : https://srv.tt-rss.org/tt-rss, I've just tested that.
So the problem is not about the url or https:// or port... it is really link to the fact that ttrrss and https://antoine.leprette.fr/site/ blog are on the same yunohost server.
That's sad because it means users of one yunohost server can't follow rss feed of other users of the same server which is sad for family sharing one yunohost server.

**Comment by Thatoo** [comment]
@ericgaspar is there really no solution any more to follow an rss feed from a blog hosted locally in yunohost? ttrss lose a lot of interest then to be installed on yunohost.

**Comment by MonsieurPoutounours** [comment]
Hi,

I am using the same issue on a different context : TT-RSS and Bridge RSS on the same server. 

Can't follow anything local too. Could an option (opt-in) be added to help us remove this behavior ?

**Comment by Thatoo** [comment]
Awesome! apparently, the last update solved that issue. Waiting for confirmation but this issue might be soon closed.

**Comment by Thatoo** [comment]
So I can confirm that ttrss is again able to ftech rss feed from local website, localy hosted by Yunohost.

**Comment by ballinger** [comment]
finally hosting everything through ynh, webpage with rss service through my_webapp / automad. the feed is working on local desktop aggregators, and some random android app. ttrss however prints something bout localhost...
`Couldn't download the specified URL: URL hostname failed to resolve or resolved to a loopback address (127.0.0.1)`
[automad thread](https://github.com/marcantondahmen/automad/issues/195) suggested adding a server env variable, which i did but didnt change anything.
version: 20250225~ynh1
