### ISSUE TITLE
Upstream code repository has been moved

### ISSUE THREAD

**Issue by smarthomeproxy** [YunoHost-Apps/ttrss_ynh#155]
### Context & Description: 

Unable to install tt-rss using YunoHost because the script is using the wrong domain

### Steps to reproduce
Attempt to install using YunoHost

### Expected behavior

Install works

Actual behavior: An error is shown, it looks like the domain https://git-gitea.tt-rss.org can't be reached 

### Logs

https://paste.yunohost.org/raw/buxucaruci

**Comment by tituspijean** [comment]
Their forge has moved to https://gitlab.tt-rss.org/tt-rss/tt-rss

**Comment by ericgaspar** [comment]
Closing with #154

**Comment by ericgaspar** [comment]
closing #154
