### ISSUE TITLE
Login display previous user data

### ISSUE THREAD

**Issue by kemenaran** [YunoHost-Apps/ttrss_ynh#16]
Hi! Thanks for your great work on Yunohost and TTRSS. I found an issue where you can see and edit other peoples feeds if you connect after the previous user disconnected :

1. Access TinyTinyRSS without being authenticated on the Yunohost server
2. Authenticate with your login password as user "A". TTRSS loads and display user "A" feeds
3. Disconnect from Yunohost (for instance using the Yunohost Icon at the bottom of the screen)
4. Log in as Yunohost user "B"
5. Access TTRSS : you will be connected as user "A" and see, edit and remove all his/her feeds.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/500

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
