### ISSUE TITLE
Broken feed update on jessie

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/ttrss_ynh#18]
On jessie, www-data has no available shell by default.

```
admin@ynh:~$ cat /etc/passwd | grep www-data
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
admin@ynh:~$ sudo su -c "cd /var/www/ttrss && /usr/bin/php /var/www/ttrss/update.php --feeds" www-data
This account is currently not available.
```

So the automated feeds update is broken

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/498

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
