### ISSUE TITLE
Public opml link requires authentification

### ISSUE THREAD

**Issue by DamienCassou** [YunoHost-Apps/ttrss_ynh#22]
When going to the 2nd tab ("Flux" in French version) of the configuration panel in TTRSS, you can get a public URL of your OPML. This can be used to share your RSS feeds or to backup them.

Unfortunately, in yunohost, this URL requires yunohost authentification and is thus not public.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/497

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
