### ISSUE TITLE
Broken images when "cache images locally" is selected

### ISSUE THREAD

**Issue by malmsey** [YunoHost-Apps/ttrss_ynh#25]
Has anyone else had this issue?  I'm not sure where to begin to troubleshoot.  Embedded images appear as broken links when ttrss tries to load them from cache instead of from feed website.  Would be a nice feature to have working!

**Comment by malmsey** [comment]
Just to clarify, the message I get in Firefox is: "cached image cannot be displayed because it contains errors"
And when I view the source I see lots of strange characters like "��U����1�V�ڶ��T�Q�"

I tried deleting blank lines in my config files as suggested here 
https://tt-rss.org/forum/viewtopic.php?f=1&t=3728&p=22093&hilit=cannot+be+displayed+contains+errors&sid=5689930b6bfdd0e60b566a123dae3557#p22093
but it has had no effect.

Does anybody using this package have image caching working?

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/496

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
