### ISSUE TITLE
Public User ?

### ISSUE THREAD

**Issue by benborges** [YunoHost-Apps/ttrss_ynh#27]
How do I turn one of my user subscriptions public ? 
basically I want to be able to access the feeds from the wide internet without
having the SSO asking me to login. 

Users should not be able to add new RSS feeds or mark them as read, but they could use the feed reader to consult the information presented. 

is that possible ? 

inside var/www/ttrss there config.php and inside there is :

define('SINGLE_USER_MODE', false);
// Operate in single user mode, disables all functionality related to
// multiple users and authentication. Enabling this assumes you have
// your tt-rss directory protected by other means (e.g. http auth).

is there any chance I can enable this to True and have all users use the same RSS subscriptions ?
that would be already a good solutions, since my users don't know how to use RSS.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/494

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
