### ISSUE TITLE
Update ttrss upgrading model

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/ttrss_ynh#32]
Tiny tiny RSS now uses a [rolling release](https://tt-rss.org/fox/tt-rss/wikis/home#download) model based on git master branch which is considered stable. The YunoHost package should be updated to get sources from a specific commit on the gitlab repository.

**Comment by rndmh3ro** [comment]
How exactly would this be accomplished? Would someone update this repo everytime a new commit gets pushed into the tt-rss repo?

**Comment by JimboJoe** [comment]
This package should download the sources corresponding to a specific commit on master.
Policy on official package update is still very flexible, so whether we should/will/will have enough time to update this package to reference a newer commit isn't fixed ;-)
Do you feel like getting this new upstream source downloading implemented ? :-)

**Comment by rndmh3ro** [comment]
Actually there's nothing to change in the code to be able to download specific commits.

The URL where the zip gets downloaded is `https://tt-rss.org/gitlab/fox/tt-rss/repository/archive.zip?ref=${VERSION}`

$VERSION is a reference, so it can be a version number or a commit or other things.
So to update the version, we just have to change the version number to a commit id.
