### ISSUE TITLE
After upgrading - update daemon not running

### ISSUE THREAD

**Issue by 1989gironimo** [YunoHost-Apps/ttrss_ynh#46]
After updating ttrss yesterday, I don't get any updates from my feeds.
It just says "update daemon not running"

Using ttrss 17.4 on yunohost 2.7.5

If you need logs or something like that, I'm more than happy to provide them to you but I can't find the directory where they're in.

**Comment by maniackcrudelis** [comment]
@ariasuni can you have a look at this issue please ?

**Comment by Jibec** [comment]
I had the same issue and tried to upgrade manually with `sudo yunohost app ugrade ttrss` but it said:
> Source path '/etc/cron.d/ttrss' does not exist

If fixed it with `sudo touch /etc/cron.d/ttrss` and ran again `sudo yunohost app ugrade ttrss`.

**Comment by 1989gironimo** [comment]
I cannot update the app because it is already upgraded.
The only possibility would be to manually fix the cron-file from the zip-archive.

**Comment by 1989gironimo** [comment]
@Jibec Can you please post the content of the cron-file, to fix that manually?

**Comment by Jibec** [comment]
Well, just connect to your server in ssh (ssh admin@yourdomain.me) and then type the two commands I wrote. The command "touch" only create an empty cron file so the backup works and the update can be run.

If you did not open the port 22 for ssh on your router or internet box, you can still run it from inside your network (like another PC of your house).

You can update a package several time, even if it is a the same version, most apps supports it without problem, no worries. It is one of the basic quality tests we run for each apps. I think it is specifically for this kind of situation.

**Comment by 1989gironimo** [comment]
I know the touch command and what it does, but thanks anyway :)
After the creation of the file (and several reboots, etc.) it still says, that the update daemon doesn't work, so I thought about inserting the command and a fitting interval (every 30 mins or something like that) but I don't know the path to the executable - the reason why I'm asking you about the content...

If I try to update ttrss via the yunohost cli it says the following:
`yunohost app upgrade ttrss
Success! ttrss is already up to date
Error: No app to upgrade
`

**Comment by maniackcrudelis** [comment]
The cron file contained that:
```*/30 * * * * $app cd $final_path && /usr/bin/php $final_path/update.php --feeds >/dev/null 2>&1```

@ariasuni seems to not be around here. I have something else to fix right now, but after that, I will have a look at this problem.

**Comment by 1989gironimo** [comment]
Even after inserting the command and a reboot, still not working..

**Comment by maniackcrudelis** [comment]
Of course you have changed the contains of the given line !?
You can try to remove the redirection to /dev/null and redirect to a file to have a log.

**Comment by 1989gironimo** [comment]
I've definitely do something wrong while editing this file:
`*/30 * * * * ttrss cd /var/www/ttrss && /usr/bin/php /var/www/ttrss/update.php --feeds >/home/0x0000001/ttrss.log 2>&1
`

**Comment by maniackcrudelis** [comment]
So... I tried ttrss today.
Even if ttrss need a lot of patience, it works fine. And my feeds are up to date.

And, after an upgrade my service ttrss run correctly.
If you still have your script systemd, can you try to reboot ttrss please ?

**Comment by 1989gironimo** [comment]
Well, I've rebooted the system several times and replaced the cron file with that line from above.
(If that's what you mean)

**Comment by maniackcrudelis** [comment]
Err, no that's not what I meant.
My proposition was to restart ttrss only.

`sudo systemctl restart ttrss`
Then
`sudo journalctl -u ttrss`
To see if is always good with the service.

And by the way, do not keep the cron file.
But, you can keep the cron file if you prefer and remove or stop the service.

**Comment by ariasuni** [comment]
Also, keep in mind that scripts assume there’s a systemd file (the backup script for example) so it’s probably better to use stop and disable the service with `sudo systemctl stop ttrss && sudo systemctl disable ttrss` than removing the file, if you absolutely don’t want to use the systemd service.

**Comment by 1989gironimo** [comment]
I think the manual reboot of the ttrss service helped, it's working now!

**Comment by 1989gironimo** [comment]
Had it again the last three days, restarted it manually again and it's working again.

**Comment by maniackcrudelis** [comment]
Can you check your log to see if anything happened before the crash of the service?

**Comment by hirgelbirgel** [comment]
After upgrading/migration to yunohost 2.7.14 on debian stretch i got the same problem. I already tried the solution with "touch", upgrade as well as reboot/restart service. The log says:
```
Jun 25 07:17:02 YunoHost systemd[1]: Started ttrss_backend.
Jun 25 07:17:02 YunoHost php[23654]: Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade.
Jun 25 07:17:02 YunoHost php[23654]: Please fix errors indicated by the following messages:
Jun 25 07:17:02 YunoHost php[23654]:  * PHP support for MySQL is required for configured DB_TYPE in config.php.
Jun 25 07:17:02 YunoHost php[23654]: You might want to check tt-rss wiki or the forums for more information.
Jun 25 07:17:02 YunoHost php[23654]: Please search the forums before creating new topic for your question.
Jun 25 07:17:02 YunoHost systemd[1]: ttrss.service: Main process exited, code=exited, status=255/n/a
Jun 25 07:17:02 YunoHost systemd[1]: ttrss.service: Unit entered failed state.
Jun 25 07:17:02 YunoHost systemd[1]: ttrss.service: Failed with result 'exit-code'.
```
Do you have any idea to solve this?

**Comment by JimboJoe** [comment]
Is the `php-mysql` package present (`dpkg -l |grep php-mysql`)?

**Comment by hirgelbirgel** [comment]
I checked it, and no, it is not present.

**Comment by ericgaspar** [comment]
@baboonandsloth This issue is 4 years old... please open a new issue with logs.
