### ISSUE TITLE
Public feed isn't accessable from the public net

### ISSUE THREAD

**Issue by GeekAnnoyed** [YunoHost-Apps/ttrss_ynh#49]
Hello, 
I've just been playing with the ttrrs package and it's awesome but I've found a bug/feature
The feature for shared public feeds isn't' publically accessible due to the nature of yunohost and the protection for services it offers.

you can find this setting under https://example.com/ttrss/prefs.php and then feeds> Published & shared articles
```
https://example.com/ttrss/public.php?op=rss&id=-2&view-mode=all_articles&key=mysecretkey
```
I've no idea how to debug this sorry.

```
 Versions

yunohost
    2.7.9 (stable)
yunohost-admin
    2.7.7 (stable)
moulinette
    2.7.7 (stable)
ssowat
    2.7.7 (stable) 

tinyrss Install time 10/2/2018
```

**Comment by xpd259** [comment]
after some research, I found that this command fixed it for me
sudo yunohost app setting ttrss skipped_uris -v "/public.php"
sudo yunohost app ssowatconf
this seems to have allowed access to the public URL
