### ISSUE TITLE
UTF-8 problems with MySQL, not present in PostgreSQL

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/ttrss_ynh#52]
When using MySQL (as it is configured at installation in yunohost), tt-rss has problems with RSS titles containing emojis.
Here is a comparison between tt-rss using postgresql and using mysql (for the same feed)

![image](https://user-images.githubusercontent.com/693751/40054630-dcfce8b0-5845-11e8-8883-9bb32d36ae73.png)
![image](https://user-images.githubusercontent.com/693751/40054635-dfe5743e-5845-11e8-9fda-f0cb472da615.png)

Is it possible to make tt-rss use postgreSQL, at least during the installation ? (I have no idea of the impact it can have for already existing installations)

**Comment by Josue-T** [comment]
Hello,

I don't really know about ttrss but there are also a discussion about nextcloud https://github.com/YunoHost-Apps/nextcloud_ynh/issues/107

In my point of view it could be a good idea to migrate to postgresql, but I think in all case, the migration will be not easy.

**Comment by supermamie** [comment]
I'm not really sure a migration is possible (according to https://discourse.tt-rss.org/t/migration-from-mysql-to-postgresql/265/13 )
What can at least be done is that fresh installs use PostgreSQL, and already used installs stays with MySQL.

According to the linked thread, the only way to do this, without losing everything (but not keeping everything either) is to export the OPML, and export saved articles, then re-import them in another tt-rss.
I have no idea if there is an automatic way of doing this (I did it manually when I switched on my server, but it is still not a yunohost, I'm still testing on a VM)

**Comment by ericgaspar** [comment]
There is a branch for testing ttrss with PostgreSQL (there is no migration from MySQL. You may want to use a multi instance to keep your previous version of ttrss safe) https://github.com/YunoHost-Apps/ttrss_ynh/tree/PostgreSQL

**Comment by ericgaspar** [comment]
Closing following the (hard) transition to PostgreSQL
