### ISSUE TITLE
Script cannot doanload the archive file from git repo

### ISSUE THREAD

**Issue by DoumeDuSud** [YunoHost-Apps/ttrss_ynh#71]
As share on Matrix : https://matrix.to/#/!wHVnMtPcnHpqRVncZG:matrix.org/$15755650713178eOBpp:matrix.ds-guiraud.fr?via=matrix.org&via=matrix.ds-guiraud.fr&via=homecore.space

I have an error when I want to install Tiny RSS. I think it's because the structure of Git répo is change by the owner. The link to download should be like that : 
https://git.tt-rss.org/fox/tt-rss/archive/1.15.3.tar.gz

error past message : https://paste.yunohost.org/raw/uhiconehop
Thanks for all the job already done :+1:

**Comment by JimboJoe** [comment]
Thanks for the report!
Given [this official statement](https://community.tt-rss.org/t/versioning-changes-for-trunk/2974/18), the tt-rss maintainer has disabled the way to retrieve tagged archives of tt-rss to only allow pulling master latest sources from git.
So one has to come up with a different way of managing this to enable maintaining this YunoHost package again...

**Comment by toitoinebzh** [comment]
I confirm this issue
https://forum.yunohost.org/t/error-unable-to-upgrade-ttrss/9749

**Comment by DoumeDuSud** [comment]
Merci beaucoup :+1: 
Thanks a lot

**Comment by TheNomad11** [comment]
Address has changed again. 

`Could not fetch sources files, is the URL correct?`

`unable to download https://github.com/YunoHost-apps/ttrss_ynh/archive/07c0a85cf4adf9740790a6331a1f8c7a1ddb454e.zip`
