### ISSUE TITLE
ttrss_backend not activating since last update

### ISSUE THREAD

**Issue by daprofessa19** [YunoHost-Apps/ttrss_ynh#74]
Hi,

Since the last update, the ttrss_backend will not activate and the multi-process update script will not run.

After running `sudo journalctl -u ttrss` I see the below repeatedly.

`Started ttrss_backend.
error: This script requires PHP compiled with PCNTL module.
ttrss.service: Service hold-off time over, scheduling restart.
Stopped ttrss_backend.`

Thanks

**Comment by yalh76** [comment]
should be solved with last version
