### ISSUE TITLE
using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated

### ISSUE THREAD

**Issue by strasbourgcurieux** [YunoHost-Apps/ttrss_ynh#77]
Hello
here's the message at the top of YunoHost's installation page 

/!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.

**Comment by yalh76** [comment]
New permission system has been integrated
