### ISSUE TITLE
Problem with admin users

### ISSUE THREAD

**Issue by ZeHiro** [YunoHost-Apps/ttrss_ynh#8]
HI,
I have detected two problems (which are one) in the install of ttrss on Yunohost : 
- the default admin user is still active after install (login: admin, password: password)
- the admin user of yunohost does not have the admin rights in ttrss, which means it cannot perform an update of ttrss (I usually update my yunohost apps before the update is available through yunohost)

Thanks

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/502

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
