### ISSUE TITLE
Way of having a different password to authenticate on ttrss for android application

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/ttrss_ynh#80]
When trying to connect my ttrss install from yunohost on an android device, I was not too sure I wanted to use my main user password on a device that I might loose or is more easily hackable that some other devices I use to access my yunohost. 

I would like to find a way to not use my main password for this "subset" of my yunohost. 

There doesn't seem to be a sort of token authentication in ttrss (or I haven't found the plugin). 

But there seems to be a  `auth_internal` / `auth_remote` 

![Screenshot from 2020-07-01 11-43-28](https://user-images.githubusercontent.com/108437/86229882-9f44ea80-bb90-11ea-8e12-fdc4875b50ec.png)

I guess that `auth_remote` is used for the SSO used in yunohost (ldap auth etc.). So maybe I can have a different (less secure) password in the `auth_internal` that I could use in the android app. 

The password tab is empty, maybe that's a feature ? : 

![Screenshot from 2020-07-01 11-48-41](https://user-images.githubusercontent.com/108437/86230047-d915f100-bb90-11ea-86fc-c3483595175d.png)

Or maybe you would recommend having a send separate yunohost user which has only access to this application ? 

Thanks in advance for helping me figure a way for this (by the way I've done something similar in nextcloud which seems to work quite well with an additional android user and shares with the "normal" user).

**Comment by rndmh3ro** [comment]
Either do this: 

> Or maybe you would recommend having a send separate yunohost user which has only access to this application ?

Or create a separate user account in ttrss. You need to enable registrations in the `config.php`:

```
        define('ENABLE_REGISTRATION', true);
```

Then open ttrss in an private tab to register a new user (with a valid mail).

Afterwards disable the registration again.

**Comment by yalh76** [comment]
you can now directly create a new user without opening registration
