### ISSUE TITLE
LibXML Error with thefarside.com

### ISSUE THREAD

**Issue by tetchey** [YunoHost-Apps/ttrss_ynh#81]
I have a feed URL pointing to **`https://www.thefarside.com/`**

The `af_comics` plugin is enabled and should be able to parse the site to create a dynamic feed, however this feed is being highlighted as having update errors. Hovering over the feed name on the left reveals a pop-up stating
`LibXML error 41 at line 21 (column 59): Specification mandate value for attribute crossorigin`

I can confirm that the non-ynh version of tt-rss works correctly with this site.

**Comment by ericgaspar** [comment]
I am trying to replicat this error. What is the actual feed URL for this site?
W3C validator is not validating https://www.thefarside.com/ as a valid feed...
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.thefarside.com%2F

**Comment by tetchey** [comment]
Thanks @ericgaspar. The URL is simply https://www.thefarside.com/

With the af_comics plugin, the plain site URL is transformed into a feed.

**Comment by ericgaspar** [comment]
I did a PR #82 which updates ttrss_ynh to upstream and PHP to 7.3. In my server (YunoHost 4.0.4) with af_comics plugin enabled I can import the link... (The CI fails with *change_url* script :/  so there is still work to do...)

**Comment by ericgaspar** [comment]
This issue should be solved with #82

**Comment by tetchey** [comment]
I can confirm that it is now working correctly.

Thank you very much!
