### ISSUE TITLE
YunoHost 4.0.7 (stable)  install error Exception while creating PDO object:could not find driver

### ISSUE THREAD

**Issue by R-0ne** [YunoHost-Apps/ttrss_ynh#83]
hi, the installation made an error under Yunohost 4

DEBUG - + sudo -u ttrss php /var/www/ttrss/update.php --update-schema
DEBUG - <pre>Exception while creating PDO object:could not find driver</pre>+ ynh_exit_properly
DEBUG - + local exit_code=101sudo -u ttrss php /var/www/ttrss/update.php --update-schema
DEBUG - <pre>Exception while creating PDO object:could not find driver</pre>+ ynh_exit_properly
DEBUG - + local exit_code=101

all the log is here:
https://paste.yunohost.org/raw/ovenesarop

Thanks

**Comment by SimonMellerin** [comment]
It seems that this package does not install all php extension needed for TTRSS.

Should be fixed with https://github.com/YunoHost-Apps/ttrss_ynh/pull/82

**Comment by NicolasBrosse** [comment]
Hello,
I have the same issue as @R-0ne 
with the following log : https://paste.yunohost.org/raw/ugovezever

**Comment by ericgaspar** [comment]
Should be solved with #82
